version: '3.0'
services:
  thream-api:
    build:
      context: './'
    ports:
      - '8080:8080'
    volumes:
      - './:/app'
      - '/app/node_modules'
      - '/app/build'
    container_name: 'thream-api'
